### ISSUE TITLE
Vending-Machine 요구사항 분석

### ISSUE THREAD

**Issue by dev-angelo** [codesquad-memeber-2020/vm-3#1]
Vending-Machine 기획서 (https://docs.google.com/presentation/d/1ddYpZAlesP0rkjnumy6Lc2PcPYAJTmAdJHW98GI5QXI/edit#slide=id.g7c02551fdc_1_80) 를 통한 요구사항분석

**전체화면 >**
![vending-machine](https://user-images.githubusercontent.com/58318174/76277037-e568fc00-62ca-11ea-8615-7f6cc587d9d8.png)

- [x] 상품화면 분석

- [x] 상품 선택화면 분석

- [x] 지갑화면 분석

**Comment by dev-angelo** [comment]
<지갑화면 분석>

![screen_wallet](https://user-images.githubusercontent.com/58318174/76277441-1695fc00-62cc-11ea-8f08-1cf48817db50.png)


Visual:
1. 사용자가 투입 할 수 있는 금액의 종류를 보여준다.
2. 각 투입 할 수 있는 금액의 카운트를 보여준다.
3. 투입 할 수 있는 총 금액을 보여준다.

Functional: 
1. 사용자가 투입 할 수 있는 금액의 종류를 누를 수 있다.

->
1. 지갑화면에서 선택 한 금액의 카운트가 1 줄어든다
2. 지갑화면에서 투입 할 수 있는 총 금액이 선택한 금액만큼 줄어든다.
3. 상품 선택화면의 투입 금액이 사용자가 선택 한 금액만큼 증가한다.
4. 상품화면에서 상품 선택화면에 나타나는 투입 금액으로 선택 가능한 상품이 focus 된다.

**Comment by dev-angelo** [comment]
<상품화면 분석>
![screen_product](https://user-images.githubusercontent.com/58318174/76278364-df751a00-62ce-11ea-90fb-da1e07f84bed.png)

Visual:

1. 사용자가 선택 할 수 있는 상품에 대한 list 를 보여준다.
2. 상품 선택화면에 투입된 금액에 따라 선택 할 수 있는 상품을 focus 처리

**Comment by Elllin** [comment]
<상품 선택화면 분석>
![1](https://user-images.githubusercontent.com/50837520/76278667-793cc700-62cf-11ea-8832-0cb685f92c8e.jpg)
Visual:

1. 사용자가 지갑화면에서 누른 금액을 보여준다.
2. 상품번호를 누를 수 있는 번호와 선택을 확인하는 ok버튼, 취소하는 cancel버튼을 보여준다.
3. 투입한 금액, 선택한 상품, 반환해줄 잔돈등 모든 이벤트 진행 상황을 보여준다. 
 
Functional:

사용자가 선택할 상품의 번호를 누를 수 있다.
->

1. 5초안에 선택이 되는지 카운트를 센다.
 1-1. 5초안에 선택이 되지 않으면 투입금액을 반환한다.
 1-2. 5초안에 선택이 되면 상품이 선택된다.
		1-2-1. 금액이 추가로 투입되면 상품번호를 다시 누를 수 있다. (5초 대기)
2. ok버튼을 누를 시 5초 대기는 끝난다. (상품이 선택된다.)
3. cancel버튼을 누를 시 5초 대기가 끝난다. (상품 선택이 취소된다.)

**Comment by dev-angelo** [comment]
OK 버튼이랑 Cancel 버튼도 추가됐으니 그거에 대한 요구사항도 정리 되면 좋겠습니다~~

**Comment by Elllin** [comment]
2번 3번 괄호안에 상품이 선택/취소되는 내용은 상품화면에서 처리되는 영역인데 여기서 작성을 해줘야하는지 궁금합니다!

**Comment by dev-angelo** [comment]
네 맞아요 ~ 다른 영역에서 처리되는 내용이지만 명시는 해놓는게 좋을것 같아요 ㅎㅎ
시그널은 특정 화면이지만 다른 화면에도 영향을 미치는 내용에 대해서는 어떻게 정리해야 할지 추후에 의논하면 좋겠네요!
