### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by dev-angelo** [codesquad-memeber-2020/vm-3#16]
**<상품화면>**
* 상품 클릭
- [x] : 등록된 이벤트가 발생하여 Controller 의 callback (_handleProductButtonClicked) 호출

**<상품 선택화면>**
* 번호 클릭
- [x] : 등록된 이벤트가 발생하여 Controller 의 callback (_handleNumberButtonClicked) 호출

* OK 클릭
- [x] : 등록된 이벤트가 발생하여 Controller 의 callback (_handleOKButtonClicked) 호출

* Cancel 클릭
- [x] : 등록된 이벤트가 발생하여 Controller 의 callback (_handleCancelButtonClicked) 호출

**<지갑 화면>**
* 금액 클릭
- [x] : 등록된 이벤트가 발생하여 Controller 의 callback (_handleMoneyButtonClicked) 호출

**Comment by dev-angelo** [comment]
Due to 03/12

**Comment by crongro** [comment]
유닛테스트 까지? 🥇

**Comment by dev-angelo** [comment]
상품 화면-상품 클릭, 지갑 화면-금액 클릭 완료

**Comment by dev-angelo** [comment]
> 유닛테스트 까지? 🥇

Unit 테스트를 할 수 있는 환경을 만들면 좋았는데,
위 작성한 방법으로라도 진행하려고 하였습니다.

다음주 Phase_2 때는 Unit 테스트를 구축 할 수 있는 방법을 고민 해 보겠습니다~!

**Comment by Elllin** [comment]
상품 선택화면 - 번호 클릭, OK 클릭, Cancel클릭 완료
